- CHANGELOG.md
- lib/cobra_commander/affected.rb
- lib/cobra_commander/change.rb
- lib/cobra_commander/cli.rb
- spec/cobra_commander/affected_spec.rb
- spec/cobra_commander/cli_spec.rb
Adds a `name` option for the `changes --results` command.  This outputs the component names and not the full test paths.
> Component name output

- CHANGELOG.md
- lib/cobra_commander/affected.rb
- lib/cobra_commander/component_tree.rb
- spec/fixtures/app/node_manifest/package.json
Scraping the `package.json` currently only looks at `"dependencies"`.  This PR adds `"devDependencies"`.
> Add breaking scenario as devDependency

- lib/cobra_commander/formatted_output.rb
- spec/cobra_commander/cli_spec.rb
This fixes the following issue. (before top, after bottom)
> Fix bar placement issue

- lib/cobra_commander.rb
- lib/cobra_commander/cli.rb
- lib/cobra_commander/component_tree.rb
- lib/cobra_commander/executor.rb
- lib/cobra_commander/output.rb
- spec/cobra_commander/executor_spec.rb
Introduce `cobra do` to run commands within a component context
```
$ cobra do 'echo hello from $CURRENT_COMPONENT' -a spec/fixtures/app
===> a (/Users/chjunior/cobra_commander/spec/fixtures/app/components/a)
hello from a
===> b (/Users/chjunior/cobra_commander/spec/fixtures/app/components/b)
hello from b
===> g (/Users/chjunior/cobra_commander/spec/fixtures/app/components/g)
hello from g
===> e (/Users/chjunior/cobra_commander/spec/fixtures/app/components/e)
hello from e
===> f (/Users/chjunior/cobra_commander/spec/fixtures/app/components/f)
hello from f
===> c (/Users/chjunior/cobra_commander/spec/fixtures/app/components/c)
hello from c
===> d (/Users/chjunior/cobra_commander/spec/fixtures/app/components/d)
hello from d
===> node_manifest …
```
> Introduce `cobra do`

- README.md
While doing the setup of the code I realized some tests were failing due to have graphviz missing in my local environment. This PR is to add this instruction to the documentation so you can have everything properly setup before you can run the tests.
> Adds instructions to install graphviz

- CHANGELOG.md
- README.md
- lib/cobra_commander.rb
- lib/cobra_commander/cached_component_tree.rb
- lib/cobra_commander/calculated_component_tree.rb
- lib/cobra_commander/change.rb
- lib/cobra_commander/cli.rb
- lib/cobra_commander/component_tree.rb
- lib/cobra_commander/graph.rb
- spec/cobra_commander/calculated_component_tree_spec.rb
- spec/cobra_commander/change_spec.rb
- spec/cobra_commander/cli_spec.rb
- spec/cobra_commander/graph_spec.rb
This helps when we want to repeatedly run cobra on an app whose component tree hasn't changed, such as in a CI build. Calculating the component tree is the most expensive part of invoking cobra_commander.
> Allow caching component tree for faster output

- .travis.yml
- CHANGELOG.md
- lib/cobra_commander/calculated_component_tree.rb
- spec/fixtures/app/package.json
Changes implementation, instead of iterating over the items declared on workspaces, we instead use `yarn workspaces info` result to get the list of workspaces.
> Gets workspaces from yarn command

- .github/workflows/ci.yml
- CHANGELOG.md
- cobra_commander.gemspec
- lib/cobra_commander/cli.rb
- lib/cobra_commander/executor.rb
- lib/cobra_commander/executor/multi_exec.rb
- spec/cobra_commander/executor/multi_exec_spec.rb
- spec/cobra_commander/executor_spec.rb
`cobra exec` runs everything at the same time right now, consuming a lot of CPU and in some cases opening too many files in the OS.
This PR introduces the argument `--concurrency` or `-c` to `cobra exec` so the user can limit the concurrency. This argument defaults to half the number of processors of the current machine.
> Allows user to limit the concurrency of cobra exec

- CHANGELOG.md
- lib/cobra_commander/cli.rb
- lib/cobra_commander/cli/filters.rb
- spec/cobra_commander/cli_spec.rb
`cobra ls` and `cobra exec` can both take filters in the format of `--dependents` and `--dependencies`. These filters do not include the component itself. Whether it's debatable if the component is a dependency of itself, it's not debatable that the majority of the time where we use these filters we want to include the component itself in there. The majority of times where I have to run `cobra exec --dependents` of something I find myself running the same command for that component as well.
This PR adds `--self` and `--no-self`, where `--self` is the default behavior.
> Include self filter

- .github/workflows/ci.yml
- Rakefile
- cobra_commander.gemspec
- lib/cobra_commander/affected.rb
- lib/cobra_commander/change.rb
- lib/cobra_commander/cli.rb
- lib/cobra_commander/cli/filters.rb
- lib/cobra_commander/component.rb
- lib/cobra_commander/dependencies/bundler.rb
- lib/cobra_commander/dependencies/yarn/package.rb
- lib/cobra_commander/dependencies/yarn_workspace.rb
- lib/cobra_commander/executor.rb
- lib/cobra_commander/executor/concurrent.rb
- lib/cobra_commander/executor/context.rb
- lib/cobra_commander/output/ascii_tree.rb
- lib/cobra_commander/output/graph_viz.rb
- lib/cobra_commander/output/interactive_printer.rb
- spec/cobra_commander/affected_spec.rb
- spec/cobra_commander/change_spec.rb
- spec/cobra_commander/cli_spec.rb
- spec/cobra_commander/executor/concurrent_spec.rb
- spec/cobra_commander/executor_spec.rb
- spec/cobra_commander/output/graph_viz_spec.rb
- spec/cobra_commander/umbrella_spec.rb
Switch from rubocop to standardrb to align with community standards
- Switch rubocop by standardrb
- Update to standardrb format
- Update workflow to run standardrb
> Switch from rubocop to standardrb

- README.md
- cobra_commander.gemspec
- lib/cobra_commander.rb
An initial fix was done in #56 but there were some other links missing.
> Fix cbra.info links

- gemfiles/bundler2.gemfile
Make the version requirement more loose so it will not break on minor bundler updates in the CI environment.
This also follow the same pattern we require for bundler v1.
Background:
CI is still breaking because of bundle v2 updates. See: https://github.com/powerhome/cobra_commander/actions/runs/1751150571
> Update bundler requirement to fix CI

- docs/CHANGELOG.md
- docs/README.md
- lib/cobra_commander/cli/filters.rb
- spec/cobra_commander/cli_spec.rb
Allows multiple components to be targeted on `cobra ls` and `cobra exec`.
I.e.:
Execute the same command on a, b, and c:
`cobra exec a,b,c "echo hello"`
Execute the same command on a and b, and all its dependents:
`cobra exec --dependents a,b,c "echo hello"`
> Multiple target components

- lib/cobra_commander.rb
Remove unused/broken methods from CobraCommander API. These methods refer to unexisting classes that are no longer necessary (due to performance improvements) and were removed long ago.
> Remove unused/broken methods from CobraCommander API

- lib/cobra_commander/dependencies/bundler.rb
- spec/cobra_commander/cli_spec.rb
Yarn already considers all workspace packages a dependency of umbrella.
This changes bundle so it also does that. In practical terms, this changes
nothing.
> Standardize behavior between yarn and ruby packages

- cobra_commander/lib/cobra_commander/executor/command.rb
- cobra_commander/lib/cobra_commander/executor/package_criteria.rb
- cobra_commander/spec/cobra_commander/executor/command_spec.rb
- docs/README.md
Allow a job to be run conditionally:
I.e.:
```yaml
sources:
:ruby:
commands:
database:
if:
depends_on: database
run: build database
```
> Add depends_on criteria for cobra commands

- cobra_commander/lib/cobra_commander/cli.rb
- cobra_commander/lib/cobra_commander/executor/execution.rb
- cobra_commander/lib/cobra_commander/umbrella.rb
- cobra_commander/spec/cobra_commander/cli_spec.rb
- cobra_commander/spec/fixtures/app/cobra.yml
Fails when `cobra exec` or `cobra cmd` fails any job
> Fail execution when a command fails

- cobra_commander/lib/cobra_commander/umbrella.rb
- cobra_commander/spec/cobra_commander/umbrella_spec.rb
umbrella#resolve can't currently resolve when a package path partially matches the path of another.
> Fix umbrella resolve

- cobra_commander/lib/cobra_commander/affected.rb
- cobra_commander/lib/cobra_commander/umbrella.rb
- cobra_commander/spec/cobra_commander/affected_spec.rb
- cobra_commander/spec/cobra_commander/cli/output/change_spec.rb
- cobra_commander/spec/cobra_commander/umbrella_spec.rb
`Umbrella#resolve` was unable to resolve a path relative to the project, this PR switches the resolve method to only accept Pathname, and therefore it can find the realpath of the file.
> Fix Umbrella resolve when resolving relative paths

- cobra_commander/docs/CHANGELOG.md
- cobra_commander/lib/cobra_commander/affected.rb
- cobra_commander/lib/cobra_commander/cli.rb
- cobra_commander/lib/cobra_commander/cli/filters.rb
- cobra_commander/lib/cobra_commander/cli/output/change.rb
- cobra_commander/spec/cobra_commander/affected_spec.rb
- cobra_commander/spec/cobra_commander/cli/output/change_spec.rb
- cobra_commander/spec/cobra_commander/cli_spec.rb
Cleanup `cobra changes`, removing unused/invalid information about test scripts and the JSON format.
- Remove unused output and formats from cobra change
- Remove unused information from Cobra::Affected
> Cleanup cobra changes

- cobra_commander/Gemfile
- cobra_commander/Gemfile.lock
This direct dependency was added to hold the upgrade of contracts. This is no longer necessary as the gem who introduced this dependency have already changed their dep definition.
> Drop direct dependency to contracts
